version: "3.9"

services:
  UserService:
    image: order-management/user-service:latest
    build:
      context: .
      dockerfile: OrderManagementUserService/Dockerfile

  ProductService:
    image: order-management/product-service:latest
    build:
      context: .
      dockerfile: OrderManagementProductService/Dockerfile

  DeliveryService:
    image: order-management/delivery-service:latest
    build:
      context: .
      dockerfile: OrderManagementDeliveryService/Dockerfile

  FrontendService:
    image: order-management/frontend-service:latest
    build:
      context: .
      dockerfile: OrderManagementWebFrontend/Dockerfile