// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderManagementUserService.Database;

#nullable disable

namespace OrderManagementUserService.Migrations
{
    [DbContext(typeof(UserServiceDbContext))]
    [Migration("20260708144526_Add table Eventi")]
    partial class AddtableEventi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderManagementCommon.Events.DomainEventRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Contenuto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCompletato")
                        .HasColumnType("boolean");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Eventi");
                });

            modelBuilder.Entity("OrderManagementUserService.Models.Utente", b =>
                {
                    b.Property<Guid>("IdRaw")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Credenziali", "OrderManagementUserService.Models.Utente.Credenziali#Credenziali", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Password");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Username");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Generalita", "OrderManagementUserService.Models.Utente.Generalita#Generalita", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Cognome")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Cognome");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Nome");
                        });

                    b.HasKey("IdRaw");

                    b.ToTable("Utenti");

                    b.HasDiscriminator<string>("Ruolo").HasValue("Utente");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OrderManagementUserService.Models.Admin", b =>
                {
                    b.HasBaseType("OrderManagementUserService.Models.Utente");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("OrderManagementUserService.Models.Customer", b =>
                {
                    b.HasBaseType("OrderManagementUserService.Models.Utente");

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("OrderManagementUserService.Models.DeliveryGuy", b =>
                {
                    b.HasBaseType("OrderManagementUserService.Models.Utente");

                    b.HasDiscriminator().HasValue("DeliveryGuy");
                });
#pragma warning restore 612, 618
        }
    }
}
