// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderManagementDeliveryService.Database;

#nullable disable

namespace OrderManagementDeliveryService.Migrations
{
    [DbContext(typeof(DeliveryServiceDbContext))]
    [Migration("20260713122458_Remove ragione")]
    partial class Removeragione
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderManagementCommon.Events.DomainEventRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Contenuto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCompletato")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("MomentoCreazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Eventi");
                });

            modelBuilder.Entity("OrderManagementDeliveryService.Models.DeliveryGuy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("NumeroConsegneAttive")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DeliveryGuys");
                });

            modelBuilder.Entity("OrderManagementDeliveryService.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdProdotto")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUtente")
                        .HasColumnType("uuid");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeliveryGuyNotified")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("MomentoAcquisto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantita")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "OrderStatusRappresentation", "OrderManagementDeliveryService.Models.Order.OrderStatusRappresentation#OrderStatusRappresentation", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid?>("IdDeliveryGuyAssegnato")
                                .HasColumnType("uuid")
                                .HasColumnName("IdDeliveryGuyAssegnato");

                            b1.Property<DateTime?>("MomentoCancellazione")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("MomentoCancellazione");

                            b1.Property<DateTime?>("MomentoConsegna")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("MomentoConsegna");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Tipo");
                        });

                    b.HasKey("Id");

                    b.HasIndex("IdProdotto", "IdUtente", "MomentoAcquisto")
                        .IsUnique();

                    b.ToTable("Ordini");
                });
#pragma warning restore 612, 618
        }
    }
}
