// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderManagementDeliveryService.Database;

#nullable disable

namespace OrderManagementDeliveryService.Migrations
{
    [DbContext(typeof(DeliveryServiceDbContext))]
    partial class DeliveryServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderManagementDeliveryService.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdProdotto")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUtente")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantita")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "OrderStatusRappresentation", "OrderManagementDeliveryService.Models.Order.OrderStatusRappresentation#OrderStatusRappresentation", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid?>("IdDeliveryGuyAssegnato")
                                .HasColumnType("uuid")
                                .HasColumnName("IdDeliveryGuyAssegnato");

                            b1.Property<DateTime?>("MomentoCancellazione")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("MomentoCancellazione");

                            b1.Property<DateTime?>("MomentoConsegna")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("MomentoConsegna");

                            b1.Property<string>("RagioneCancellazione")
                                .HasColumnType("text")
                                .HasColumnName("RagioneCancellazione");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Tipo");
                        });

                    b.HasKey("Id");

                    b.ToTable("Order");
                });
#pragma warning restore 612, 618
        }
    }
}
