apiVersion: v1
kind: PersistentVolume
metadata:
  name: yugabyte-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/yugabyte

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yugabyte-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
