// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderManagementCommon.Database;

#nullable disable

namespace OrderManagementProductService.Migrations
{
    [DbContext(typeof(ProductServiceDbContext))]
    [Migration("20260708143321_fix DomainEventRow")]
    partial class fixDomainEventRow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderManagementCommon.Events.DomainEventRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Contenuto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCompletato")
                        .HasColumnType("boolean");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Eventi");
                });

            modelBuilder.Entity("OrderManagementProductService.Models.Acquisto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdProdotto")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUtente")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Momento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuantitaAcquistata")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdProdotto");

                    b.ToTable("Acquisto");
                });

            modelBuilder.Entity("OrderManagementProductService.Models.Prodotto", b =>
                {
                    b.Property<Guid>("Codice")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuantitaDisponibile")
                        .HasColumnType("integer");

                    b.HasKey("Codice");

                    b.ToTable("Prodotti");
                });

            modelBuilder.Entity("OrderManagementProductService.Models.Acquisto", b =>
                {
                    b.HasOne("OrderManagementProductService.Models.Prodotto", null)
                        .WithMany()
                        .HasForeignKey("IdProdotto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
